Repository RafaGomezGlez/WebVisualization, pull requests merged in 2021-05, with the labels that each got.

#7 First version of landing page
  README.md
  home.css
  index.html
Labels: pull request

#12 First version of web page
  .gitignore
  README.md
  home.css
  index.html
  package-lock.json
  projects.css
  projects.html
  sort/sort.css
  sort/sort.html
  sort/sort.js
Labels: Design, pull request

#15 Implementation of insertion sort #13
  sort/sort.css
  sort/sort.html
  sort/sort.js
Labels: JavaScript, algorithm

#18 Adding the animation of data changing places
  home.css
  projects.css
  projects.html
  sort/sort.html
  sort/sort.js
Labels: JavaScript, algorithm, pull request

#21 Second Version Home Page
  computer-code-software.jpg
  home.css
  images/e-commerce1.png
  images/file-search.png
  images/sorting-cards.png
  index.html
  projects.css
  projects.html
Labels: Design, pull request
